# -*- coding: utf-8 -*-
"""scraping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A85Gz1Chd0_6IhQN54t5V6-LUKlo-SzM
"""

import requests
from bs4 import BeautifulSoup 
import plotly.express as px

kun_uz = BeautifulSoup(requests.get('https://kun.uz/news/2022/05/17/abituriyentlarni-nimalar-kutyapti-imtihonlar-boyicha-asosiy-yangiliklar').text, 'html.parser').select_one('div.single-content').text

x = kun_uz.split('window.yaContextCb.push(()=>{')
my_list = []
for i in x[0].split():
      my_list.append(i)

count = {}
for word in my_list :
   if word in count :
      count[word] += 1
   else:
      count[word] = 1
count



unnes_words = ['“олдинги','“бу','–','ҳолда,','ҳамда','ҳам','ҳозирча','қолган','қараб','ўрнига','ўзи','ёки','яна','эса','энг','эмас.','эмас,','эди.','шундан','шунда','шу','ушбу','учун','уларнинг','уларга','тадан','та','сўнг','оид','мана','каби','етарлича.','дея','ва','бўлса,','бўлган','бўйича','бошқа','биринчи','бир-биридан','бир','балки','олдинги','масалан,','бунда','бу','фанга','агар','5','(ҳар','2','2,1','3','3,1','30','6']
x = []
for i in unnes_words:
  if i.isalpha():
    x.append(i.title())
for key, value in list(count.items()):
  for i in unnes_words:
    if key == i:
      count.pop(key)
  for j in x:
    if key == j:
      count.pop(key)
      
my_dict = count

sort_orders = sorted(my_dict.items(), key=lambda x: x[1], reverse=True)
tup_list = sort_orders[:10]

dict_1=dict()
for key,val in tup_list:
    dict_1.setdefault(key, []).append(val)


sort_orders = sorted(dict_1.items(), key=lambda x: x[1], reverse=True)

data = {'Сони':[i[0] for i in list(dict_1.values())], "Сўзи":list(dict_1.keys())}
fig = px.bar(data,x='Сони',y="Сўзи", color=['cyan', 0.3470585585916097,0.5251418319705748,0.3161264594415123,0.9559053821403337,0.037472257551104504,0.8225138386787917,0.9904764734064555,0.3616730383638286,0.7778716338632167], color_discrete_map="identity")

fig.update_layout(
    width=800,
    height=500
)

fig.show()

